version: '3.7'
services:
  ws:
    build: ws
    links:
      - redis
      - backend
  redis:
    image: redis
  minio:
    image: minio/minio
    volumes:
      - storage:/data
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    command: server /data
  postgres:
    image: postgres:11.3-alpine
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
  backend:
    build: backend
    links:
      - minio
      - postgres
    depends_on:
      - postgres
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - ws
      - backend
      - minio

volumes:
  storage:
  data:
