FROM node AS builder
WORKDIR /app_src
COPY frontend /app_src
RUN npm i && \
	npm run build

FROM nginx

COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY nginx/mime.types /etc/nginx/mime.types
COPY --from=builder /app_src/dist /app
COPY nginx/certificates /etc/letsencrypt
