version: '3.7'
services:
  ws:
    build: ws
    ports:
    - "8888:8888"
    links:
    - redis
    - backend
  redis:
    image: redis
  backend:
    build: backend
    ports:
      - "5000:5000"
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "80:80"
      - "443:443"
