FROM certbot/dns-cloudflare
WORKDIR /workdir
COPY nginx/.cloudflare.ini cloudflare.ini
RUN mkdir certs && \
	certbot certonly --register-unsafely-without-email --cert-path ./certs --dns-cloudflare --dns-cloudflare-credentials cloudflare.ini --agree-tos -d matchaaa.tk
RUN ls -la ./certs

FROM node AS builder
WORKDIR /app_src
COPY frontend /app_src
RUN npm i && \
	npm run build

FROM nginx

COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /app_src/dist /app
COPY --from=0 /etc/letsencrypt /etc/letsencrypt
